services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27018:27017"
    networks:
      - my-network
    volumes:
      - mongo-data:/data/db

  spring-boot-app:

    build:
      context: .
      dockerfile: Dockerfile
    image: student_api:latest
    container_name: spring-boot-app
    ports:
    - "8080:8080"
    environment:
    - SPRING_DATA_MONGODB_URI=mongodb://mongodb:27017/school
    networks:
    - my-network
    depends_on:
    - mongodb



networks:
  my-network:
    driver: bridge

volumes:
  mongo-data:
